version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    restart: always
    environment:
      - NODE_ENV=production
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sa
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
